#spring:
#  data:
#    elasticsearch:
#      cluster-name: es
#      ip: 116.196.85.236
#      port : 9300
#      pool : 1
#    logPath : 1 # 选择日志存入的方式，1 将日志存入ElasticSearch；2存入数据库

mybatis-plus:
  mapper-locations: classpath*:com/mooc/meetingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/elasticdemo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    filters: log4j,wall,mergeStat

